### ISSUE TITLE
Crate isn't #![no_std], making it incompatible with Rust for embedded systems

### ISSUE THREAD

**Issue by mangoplane** [monero-rs/base58-monero#38]
As the title explains, this crate is simple enough that it can be converted to not rely on the entire std library so that embedded Rust projects can depend on it. Please see https://docs.rust-embedded.org/book/intro/no-std.html on the necessity of a no_std Rust environment for embedded systems. There are many embedded systems that we can create, such as a hardware wallet.

I'm happy to attempt a PR, which will simply remove/replace the unnecessary std::io reference and use libcore/alloc where needed once the #![no_std] is added.

Thoughts?

**Comment by h4sh3d** [comment]
I like the idea, and it makes this library more useful indeed. If I’d do this library today I’d probably do it no std directly, so yes please do attempt a PR.

I’m happy to help you on this!

**Comment by coregrad** [comment]
Thanks @h4sh3d. I'm glad that you like the idea of fixing the no_std issue, it will definitely make the library more useful. I appreciate your approval to make a PR, and will reach out if I need any assistance during the process.
