### ISSUE TITLE
Publish 1.1.0

### ISSUE THREAD

**Issue by kayabaNerve** [monero-rs/base58-monero#44]
1.1.0 exists in this git repo yet was never published. I recently built monero-serai in a no-std environment and had to use a git dependency accordingly. Would it be possible for 1.1.0 to be published so I don't need a git dependency?

**Comment by h4sh3d** [comment]
I've released a new major version [2.0.0](https://github.com/monero-rs/base58-monero/releases/tag/v2.0.0) that should help being compatible with `no_std` environment.
